apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: sb-ns
  labels:
    app: smallboy
    type: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000       # The port exposed inside the cluster
      targetPort: 5000 # The port your container listens on
  selector:
    app: smallboy
    type: backend
