apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sb-backend-deployment
  namespace: sb-ns
  labels:
        {{- include "backendlabel" . | indent 2  }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
        {{- include "backendlabel" . | indent 4 }}
  template:
    metadata:
      labels:
        {{- include "backendlabel" . | indent 6  }}
    spec:
      containers:
        - name: sb-backend-pod
          image: {{ required "Error: Image.repository is required" .Values.backend.image.repository }}:{{ default "latest" .Values.backend.image.tag }}
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          envFrom:
            - secretRef:
                name: server-secret
          ports:
            - containerPort: {{ .Values.backend.service.port }}
