apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-service
  namespace: sb-ns
  labels:
    app: smallboy
    type: backend
spec:
  type: {{ default "ClusterIP" .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}  # The port exposed inside the cluster
      targetPort: {{ .Values.backend.service.port }} # The port your container listens on
  selector:
    app: smallboy
    type: backend
