apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-sb-database-deployment
    namespace: sb-ns
    labels:
        {{- include "datblabel" . | indent 2  }}
spec:
  template:
    metadata:
       name: sb-database-pod
       labels:
        {{- include "datblabel" . | indent 4  }}
    spec:
     containers:
      - name: sb-database-pod
        image: {{ required "Error: Image.repository is a required field" .Values.database.image.repository }}:{{ default "latest" .Values.database.image.tag }}
        ports:
            - containerPort: {{ .Values.database.service.port }}
        volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
     volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

  selector:
    matchLabels:
        {{- include "datblabel" . | indent 6  }}
  replicas: {{ .Values.database.replicaCount | quote }}
