apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-service
  namespace: sb-ns
  labels:
    {{- include "frontendlabel" . | indent 2  }}
spec:
  type: {{ default "ClusterIP" .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.database.service.port }}
  selector:
    {{- include "frontendlabel" . | indent 2  }}
