apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}sb-frontend-deployment
  namespace: sb-ns
  labels:
    app: smallboy
    type: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: smallboy
      type: frontend
  template:
    metadata:
      labels:
        app: smallboy
        type: frontend
    spec:
      containers:
        - name: sb-frontend-pod
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | quote }}
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          envFrom:
            - secretRef:
                name: client-secret
          ports:
            - containerPort: {{ .Values.database.service.port }}
