apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sb-ns
  labels:
    app: smallboy
    type: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
  selector:
    app: smallboy
    type: frontend
