apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}mongo-svc
  namespace: sb-ns
spec:
  selector:
       app: smallboy
       type: database
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.port }}
