version: '3.8'

services:
  mongo:
    image: mongo:6.0.13-jammy
    restart: always
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  mongo-data: