services:
  mongo:
    image: mongo:6.0.13-jammy
    restart: always
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: ./server
    restart: always
    env_file:
      - ./.env
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/smallboy
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - server

volumes:
  mongo-data: