frontend:
  image:
    repository: danklofan/smallboy-client
    tag: fixed
  replicaCount: 1
  service:
     type: ClusterIP
     port: 80

backend:
  image:
    repository: danklofan/smallboy-server
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000

database:
  image:
    repository: mongo
    tag: 6.0.13-jammy
  replicaCount: 1
  service:
    port: 27017

ingress:
  enabled: true
  name: smallboy-ingress
  namespace: sb-ns
  annotations: 
    kcert.dev/ingress: "managed"
    kcert.dev/solver-ingress-port: "80"
  className: nginx
  # Add these new keys:
  host: smallboy.danklofan.com
  tlsSecret: smallboy-tls
  paths:
    - path: /
      serviceName: frontend-service
      servicePort: 80
    - path: /api
      serviceName: backend-service
      servicePort: 5000
    
