apiVersion: v1 
kind: Service
metadata:
  name: backend-service
  labels:
    app: smallboy
    type: backend
spec:
 type: ClusterIP
 ports:
  - name: http
    targetPort: 5000
    port: 5000
 selector:
  app: smallboy
  type: backend