apiVersion: apps/v1
kind: Deployment
metadata:
    name: sb-frontend-deployment
    namespace: app1
    labels:
       app: smallboy
       type: frontend
spec:
  template:
    metadata:
       name: sb-frontend-pod
       labels:
          app: smallboy
          type: frontend
    spec:
     containers:
      - name: sb-frontend-pod
        image: danklofan/smallboy-client:fixed
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "768Mi"
        envFrom:
          - secretRef:
             name: client-secret
  selector:
    matchLabels:
      type: frontend
      app: smallboy
  replicas: 1
