apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sb-ns
  labels:
    app: smallboy
    type: frontend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80  # matches containerPort in Deployment
  selector:
    app: smallboy
    type: frontend
