apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcert-manager-binding
subjects:
  - kind: ServiceAccount
    name: kcert # Corrected: This must match the service account name in your pod description
    namespace: kcert
roleRef:
  kind: ClusterRole
  name: kcert-manager-role
  apiGroup: rbac.authorization.k8s.io