apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  namespace: app1
data:
  DB_URL: bW9uZ29kYitzcnY6Ly9BazA0NjIwMzpRd2VydHkxMjM0NTZAY2x1c3RlcjAuNXE5NHYubW9uZ29kYi5uZXQvc2hvcnRVcmw=
  NODE_ENV: cHJvZHVjdGlvbg==
  BASEURI: aHR0cHM6Ly9zaG9ydGVuLXVybC12Y2l0Lm9ucmVuZGVyLmNvbQ==